services:

  spring-boot:
    build: ./Translation
    restart: always
    env_file: .env
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs

  fastapi:
    build: ./app
    restart: always
    env_file: .env
    ports:
      - "8080:8080"